// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagamentoContext.Infrastructure.Context;

#nullable disable

namespace PagamentoContext.Infrastructure.Migrations
{
    [DbContext(typeof(PagamentoDbContext))]
    [Migration("20250703020836_pagamentoInitial")]
    partial class pagamentoInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PagamentoContext.Domain.Aggregates.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("PagamentoContext.Domain.Aggregates.Pagamento", b =>
                {
                    b.OwnsOne("PagamentoContext.Domain.ValueObjects.DadosCartao", "DadosCartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CVV");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("NomeTitular");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("NumeroCartao");

                            b1.Property<string>("Validade")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ValidadeCartao");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("DadosCartao");
                });
#pragma warning restore 612, 618
        }
    }
}
