name: Build & Test .NET com Warnings como Erro

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Verificar SDKs instalados
        run: dotnet --list-sdks

      - name: Restaurar dependências
        run: dotnet restore src/EducPlatform/EducPlatform.sln

      - name: Executar testes
        run: dotnet test src/EducPlatform/EducPlatform.sln --no-build --verbosity normal --environment=Development
